apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservice-app-example-canary
  name: zipkin-canary
spec:
  selector:
    matchLabels:
      app: microservice-app-example-canary
      service: zipkin-canary
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-app-example-canary
        service: zipkin-canary
    spec:
      containers:
      - env:
        image: openzipkin/zipkin
        name: zipkin-canary
        ports:
        - containerPort: 9411
        - containerPort: 9410
      restartPolicy: Always
