apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservice-app-example-canary
  name: frontend-canary
spec:
  selector:
    matchLabels:
      app: microservice-app-example-canary
      service: frontend-canary
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-app-example-canary
        service: frontend-canary
    spec:
      containers:
      - env:
        - name: AUTH_API_ADDRESS
          value: http://auth-api:8081
        - name: PORT
          value: "8080"
        - name: TODOS_API_ADDRESS
          value: http://todos-api:8082
        - name: ZIPKIN_URL
          value: http://zipkin:9411/api/v2/spans
        image: salimdrch/frontend
        name: frontend-canary
        ports:
        - containerPort: 8080
      restartPolicy: Always
