apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservice-app-example-canary
  name: todos-api-canary
spec:
  selector:
    matchLabels:
      app: microservice-app-example-canary
      service: todos-api-canary
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-app-example-canary
        service: todos-api-canary
    spec:
      containers:
      - env:
        - name: JWT_SECRET
          value: myfancysecret
        - name: TODO_API_PORT
          value: "8082"
        - name: REDIS_HOST
          value: redis-queue
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_CHANNEL
          value: log_channel
        - name: ZIPKIN_URL
          value: http://zipkin:9411/api/v2/spans
          
        image: salimdrch/todos-api
        name: todos-api
        ports:
        - containerPort: 8082
      restartPolicy: Always
