apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice-app-example
  name: zipkin
  namespace: production
spec:
  ports:
  - port: 9411
  selector:
    service: zipkin
  type: LoadBalancer