apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod
namePrefix: prod-eu-

resources:
- ../../base

patchesStrategicMerge:
- deployment.yaml
- version.yaml
- replicas.yaml
- settings.yaml
