apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod
namePrefix: prod-eu-

resources:
- ../../base

patchesStrategicMerge:
- deployment.yml
- version.yml
- replicas.yml
- settings.yml
