apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development
namePrefix: development-

resources:
- ../../base

patchesStrategicMerge:
- deployment.yaml
- version.yaml
- settings.yaml
